schema/user.yaml, swagger.yaml, v3/comment/api.yaml, v3/comment/socket.yaml, v4/follow/pubsub.yaml
=> feat(update-document): Update current document

global/error.yaml, v3/message/api.yaml, v3/message/socket.yaml
UP-4908
- Update error in swagger
=> feat(mention error): up-4908 Update error in swagger

index.html, schema/post.yaml, v3/post/api.yaml, v3/post/socket.yaml, v4/post/api.yaml, v4/post/socket.yaml
=> feat(post): up-4941 add tags field

schema/comment.yaml, schema/community.yaml, schema/post.yaml, schema/user.yaml, swagger.yaml, v4/realtime/comment/event.yaml, v4/realtime/comment/response.yaml, v4/realtime/comment/schema.yaml, v4/realtime/community/event.yaml, v4/realtime/community/response.yaml, v4/realtime/community/schema.yaml, v4/realtime/post/event.yaml, v4/realtime/post/response.yaml, v4/realtime/post/schema.yaml, v4/realtime/schema.yaml, v4/realtime/user/event.yaml, v4/realtime/user/response.yaml, v4/realtime/user/schema.yaml
JIRA: [UP-6050](https://ekoapp.atlassian.net/browse/UP-6050)
=> docs(swagger): added new section for real-time events (event-hub)

schema/network-setting.yaml, swagger.yaml, v3/network-setting/api.yaml, v3/network-setting/response.yaml
Add update moderation setting api
=> feat(up-5725): add update moderation setting api

swagger.yaml, v4/realtime/comment/event.yaml, v4/realtime/comment/response.yaml, v4/realtime/comment/schema.yaml, v4/realtime/post/event.yaml, v4/realtime/post/response.yaml, v4/realtime/post/schema.yaml
=> feat(event-hub): added real-time events for reaction on Post and Comment

schema/comment.yaml, schema/community.yaml, schema/post.yaml, schema/user.yaml, v4/realtime/comment/schema.yaml, v4/realtime/community/schema.yaml, v4/realtime/post/schema.yaml, v4/realtime/user/schema.yaml
=> feat(event-hub): expose path property in payload for Social

swagger.yaml, v1/channel/response.yaml, v1/channel/socket.yaml
https://ekoapp.atlassian.net/browse/UP-3932
=> Add missing endpoints in swagger doc for start/stop reading, mark seen in channel

schema/comment.yaml, schema/post.yaml, swagger.yaml, v3/comment/api.yaml, v3/comment/socket.yaml, v4/post/api.yaml, v4/post/response.yaml, v4/post/socket.yaml
- Add mention in post and create new version (v4)
- POST `/api/v4/posts`
- PUT `/api/v4/posts/:postId`
- RPC `v4/post.create`
- RPC `v4/update`
- Add mention in comment
- POST `/api/v3/comments`
- PUT `/api/v3/comments/:commentId`
- RPC `v3/comment.create`
- RPC `v3/comment.update`
=> feat(mention in social): up-5247, up-5275, up-5264 and up-5280 Add mention in post and comment

swagger.yaml, v4/community/api.yaml, v4/community/response.yaml, v4/community/socket.yaml
UP-5452
Update assign and remove role new version (v4) in swagger
=> feat(community role): up-5452 Update assign and remove role new version

v3/community/api.yaml, v3/community/socket.yaml
UP-5222
- Add search in get community user api
=> feat(search user): up-5222 Add search in get community user api

swagger.yaml, v4/realtime/post/event.yaml
- [UP-6294](https://ekoapp.atlassian.net/browse/UP-6294) change event name from 'afterDeleted' to 'deleted'
=> docs(realtime): UP-6294 change event name from 'afterDeleted' to 'deleted'

swagger.yaml, v2/message/api.yaml, v2/reaction/api.yaml
In Admin endpoint, move requestbody to querystring
=> feat(admin): up-6613 move requestbody to querystring

swagger.yaml, v3/role/api.yaml
change request body to query params
=> feat(role): up-6536 fix get role query

swagger.yaml, v2/channel/api.yaml, v3/channel/api.yaml
- Move query from body to query params
- fix path params
https://ekoapp.atlassian.net/browse/UP-6614
=> feat(channel): up-6614 fix params

swagger.yaml, v2/user/api.yaml, v3/comment/api.yaml
=> feat(user&comment): up-6615 fix params user & comment

v2/message/api.yaml, v3/comment/api.yaml, v3/comment/socket.yaml, v3/message/api.yaml, v3/message/socket.yaml
add properties in data field
https://ekoapp.atlassian.net/browse/UP-6832
=> feat(swagger): up-6832 adjust schema in data property

schema/moderation.yaml, swagger.yaml, v1/moderation/api.yaml, v1/moderation/response.yaml
Add document for admin query blacklist rules
=> feat(moderation): UP-7024 add get blacklist rules document

swagger.yaml, v4/post/api.yaml, v4/post/socket.yaml
=> feat(post): up-6327 query postv4

swagger.yaml, v3/notification/api.yaml
UP-4432
- Register notification v3
- POST `/api/v3/notification`
- Unregister notification v3
- DELETE `/api/v3/notification`
=> feat(Notification register): up-4432 Add register and unregister notification v3 in swagger

v4/post/api.yaml, v4/post/socket.yaml
Update post
- add `attachments` to API PUT `api/v4/post`
- add `attachments` to RPC POST `sockets/v4/post.update`
=> feat(update video post): up-8000 Update attachments in video post

global/error.yaml, swagger.yaml, v4/user/api.yaml, v4/user/response.yaml
=> chore(release): update version to 4.30.0

swagger.yaml, v4/user/api.yaml, v4/user/response.yaml
=> feat(report user): asc-1433, asc-1434 Add API v4 flag user

index.html, swagger.yaml, v1/message/api.yaml, v1/notification/api.yaml, v2/message/api.yaml, v3/comment/api.yaml, v3/community-category/api.yaml, v3/community-feed/api.yaml, v3/community/api.yaml, v3/content-feed/api.yaml, v3/file/api.yaml, v3/global-feed/api.yaml, v3/message/api.yaml, v3/network/api.yaml, v3/post/api.yaml, v3/user-feed/api.yaml, v3/user/api.yaml, v3/video-streaming/api.yaml, v4/follow/api.yaml, v4/post/api.yaml
- move request body to query params
- Fix BearerAuth
=> feat(swagger): asc-1507 fix get endpoint

v3/user/api.yaml
Adding query string "type" for support query with internal Id
type -> enum["public", "internal"]
=> feat(swagger): modify get userV3

v3/comment/api.yaml, v3/post/api.yaml, v4/post/api.yaml
create post & comment with createdAt params
=> feat(post-comment): asc-2560 create post & comment with createdAt params

swagger.yaml, v2/channel/api.yaml, v3/channel/api.yaml, v3/comment/api.yaml, v3/community/api.yaml, v3/message/api.yaml, v3/poll/api.yaml, v3/post/api.yaml, v4/comment/api.yaml, v4/community/api.yaml, v4/post/api.yaml
Remove params from the request body if it's already in the path variable
=> fix(swagger): asc-2517 fix API params

swagger.yaml, v3/channel/event.yaml
https://ekoapp.atlassian.net/browse/ASC-1968
=> feat(channel delete): asc-1968 Publish this event when channel deleted

index.html, swagger.yaml, v3/reaction/api.yaml, v3/reaction/response.yaml, v3/reaction/socket.yaml
=> feat(reaction): asc-2718 add api reaction v3

schema/network-setting.yaml, swagger.yaml, v3/network-setting/api.yaml, v3/network-setting/response.yaml
=> feat(network-setting): asc-2596 Publish API doc for update and get content check

swagger.yaml, v3/channel/api.yaml
Create HTTP API for channel.markSeen
channel.markSeen => POST /api/v3/channels/{channelId}/seen
https://ekoapp.atlassian.net/browse/ASC-1965
=> feat(channel): asc-1965 add api for channel.markSeen

swagger.yaml, v3/notification/api.yaml
Create HTTP API for the following notification RPCs
notification.getSetting => GET /api/v3/notification/setting
notification.saveSetting => POST /api/v3/notification/setting
https://ekoapp.atlassian.net/browse/ASC-1564
https://ekoapp.atlassian.net/browse/ASC-1565
=> feat(notification): asc-1564 add api for get/save notification setting

swagger.yaml, v3/user/api.yaml
Create HTTP API for user.isFlagByMe
user.isFlagByMe => GET /api/v3/users/{userId}/isFlagByMe
=> feat(users): asc-1967 add api for user.isFlagByMe

swagger.yaml, v2/reaction/api.yaml, v3/notification/response.yaml, v3/poll/response.yaml, v3/poll/socket.yaml
Fixing the wrong API description and missing response payload
https://ekoapp.atlassian.net/browse/ASC-1726
https://ekoapp.atlassian.net/browse/ASC-1972
https://ekoapp.atlassian.net/browse/ASC-2020
https://ekoapp.atlassian.net/browse/ASC-4304
=> fix(docs): asc-4304 fix api description

v3/session/api.yaml
https://ekoapp.atlassian.net/browse/ASC-4565
=> chore(swagger): update displayName maxLength

schema/channel.yaml
https://ekoapp.atlassian.net/browse/ASC-4676
=> feat(channel): asc-4676 add _id and path to channel entity

schema/message.yaml
https://ekoapp.atlassian.net/browse/ASC-4677
=> feat(message): asc-4677 add _id and path to message entity

v1/device/api.yaml, v3/session/api.yaml
=> feat(Adjust device id): asc-4876 Change validation device id to 150 char

schema/network-setting.yaml
=> feat(feed-setting): asc-4017 Add feed type message

v3/channel/api.yaml, v3/channel/socket.yaml, v3/session/api.yaml
Detail
- asc-4538 Change miximum user in conversation channel
- session Change summary title
=> feat(create conversation channel): asc-4538 Change miximum user in conversation channel

v4/post/api.yaml
=> feat(query post): asc-5087 Add post poll type

v3/session/response.yaml
https://ekoapp.atlassian.net/browse/ASC-3622
=> chore(session): asc-3622 fix response payload

v4/channel/api.yaml
https://ekoapp.atlassian.net/browse/ASC-5363
=> chore(channel): asc-5363 move body params to query params

index.html, v3/community/api.yaml, v3/community/socket.yaml
https://ekoapp.atlassian.net/browse/ASC-5445
=> feat(community): asc-5445 add type params for get v3/communities

v3/community/api.yaml
=> feat(query post): asc-5733 Add description in search for query community user

v4/channel/api.yaml, v4/channel/socket.yaml
=> feat(query channel user): asc-5803 Add description in search for query channel user

v3/post/api.yaml
Ticket
- https://ekoapp.atlassian.net/browse/ASC-6958
=> feat(query post v3): asc-6958 Edit description of hasFlag

swagger.yaml, v2/reaction/api.yaml
Add referenceVersion field for add/remove reaction API
https://ekoapp.atlassian.net/browse/ASC-5784
=> feat(reaction): asc-5784 add referenceVersion field for reaction API

v3/session/response.yaml, v4/session/response.yaml
https://ekoapp.atlassian.net/browse/ASC-6891
=> feat(session): asc-6891 change expiredAt to expiresAt

v3/reaction/api.yaml
Add field referenceVersion to query reaction v3 api
https://ekoapp.atlassian.net/browse/ASC-7961
=> feat(reaction): add field referenceVersion to query reaction v3 api

swagger.yaml, v3/poll/webhook.yaml
=> feat(vote webhook): asc-8259 Add new webhook for vote in poll

swagger.yaml
https://ekoapp.atlassian.net/browse/ASC-8097
=> feat(notification): asc-8097 add max length validation

v1/notification/api.yaml, v3/notification/api.yaml
https://ekoapp.atlassian.net/browse/ASC-9383
Add notifiableEvent name when save notification setting
=> fix(noti): asc-9383 fix notifiiable events when save noti setting

v4/post/api.yaml
https://ekoapp.atlassian.net/browse/ASC-9677
Fix description when create a custom post
=> fix(posts): asc-9677 fix description when create custom post

schema/comment.yaml, v3/comment/api.yaml
https://ekoapp.atlassian.net/browse/ASC-11053
Update comment API and schema to support media in comment
=> feat(comment): asc-11053 update comment API and schema for media in comment

swagger.yaml, v3/realtime/channel/event.yaml, v4/realtime/comment/event.yaml, v4/realtime/community/event.yaml, v4/realtime/follow/event.yaml, v4/realtime/post/event.yaml, v4/realtime/user/event.yaml, v5/realtime/message-feed/event.yaml, v5/realtime/message/event.yaml
Fix RTE section to be shown properly
=> feat(rte): fix RTE section

swagger.yaml
https://ekoapp.atlassian.net/browse/ASC-11695
Fix realtime event summary
=> fix(realtime): asc-11695 fix realtime event summary

schema/follow.yaml, swagger.yaml, v4/user/response.yaml, v5/follow/response.yaml
Ref: https://ekoapp.atlassian.net/wiki/spaces/UP/pages/2168717451/MMF1+Block+User+Ability+to+block+users.#API-Specification.1
=> feat(user-block): asc-12185 add block user API

v2/reaction/response.yaml, v3/reaction/response.yaml
Add full user and file object to query reaction API
https://ekoapp.atlassian.net/browse/ASC-12582
=> feat(reaction): asc-12582 add full user and file object to query reaction API

schema/network-setting.yaml, swagger.yaml, v3/network-setting/request.yaml, v3/network-setting/response.yaml
Add API for get/update prehook setting
https://ekoapp.atlassian.net/browse/ASC-12691
=> feat(prehook): asc-12691 add API for get/update prehook setting

swagger.yaml, v3/file/api.yaml
https://ekoapp.atlassian.net/browse/ASC-12885
=> fix(file): asc-12885 fix file api v3 params typo

schema/poll.yaml
https://ekoapp.atlassian.net/browse/ASC-6711
=> feat(poll): asc-6711 Adjust poll payload to support internal & public id

schema/video-streaming.yml
https://ekoapp.atlassian.net/browse/ASC-6724
=> feat(stream): asc-6724 Adjust stream payload to support internal & public id

swagger.yaml
https://ekoapp.atlassian.net/browse/ASC-16263
=> fix: asc-16263 Typo for Webhook Event - follow.didDeclineRequest

schema/channel.yaml, schema/message-feed.yaml, schema/message.yaml, schema/network-setting.yaml, swagger.yaml, v3/channel/response.yaml, v5/message/response.yaml
**Network-setting:**
- Update chat setting: [Amity API](https://apidocs.dev.amity.co/#/paths/api-v3-network-settings-chat/put?branch=feature-asc-16126) 
- Get chat setting: [Amity API](https://apidocs.dev.amity.co/#/paths/api-v3-network-settings-chat/get?branch=feature-asc-16126) 
**Channel v3**
- Query channel list: [Amity API](https://apidocs.dev.amity.co/#/paths/api-v3-channels/get?branch=feature-asc-16126) 
- Get channel by id: [Amity API](https://apidocs.dev.amity.co/#/paths/api-v3-channels-channelId/get?branch=feature-asc-16126)  
**Message-feed v5**
- Query Message-feed list: [Amity API](https://apidocs.dev.amity.co/#/paths/api-v5-message-feeds-list/get?branch=feature-asc-16126) 
- Query Message-feed list by channel id: [Amity …
=> feat(message preview): asc-16126 Update swagger for message preview

swagger.yaml
https://ekoapp.atlassian.net/browse/ASC-16501
=> feat(post-impression): add new analytic API endpoints document
